site_name: جزوه PostgreSQL
site_description: یک راهنمای کامل و قدم به قدم برای یادگیری پایگاه داده قدرتمند PostgreSQL است که بر اساس دوره Mastering Postgres توسط آرون فرانسیس (Aaron Francis) تهیه و بومی‌سازی شده است.
site_author: یونس جمشیدی

theme:
  name: material
  language: fa
  direction: rtl
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: تغییر به حالت تاریک
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: تغییر به حالت روشن
  features:
    - navigation.tabs
    - content.code.copy
    - content.code.annotate
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - navigation.top
    - navigation.expand
  custom_dir: overrides

extra_css:
  - styles/font_faces.css
  - styles/general.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true

nav:
  - "صفحه اصلی": "index.md"
  - "انواع داده پیشرفته":
      - "بازه زمانی (Intervals)": "advanced_data_types/023_intervals.md"
      - "نوع داده Serial": "advanced_data_types/024_serial_type.md"
      - "دنباله‌ها (Sequences)": "advanced_data_types/025_sequences.md"
      - "ستون‌های Identity": "advanced_data_types/026_identity.md"
      - "آدرس‌های شبکه و MAC": "advanced_data_types/027_network_and_mac_addresses.md"
      - "نوع داده JSON": "advanced_data_types/028_json.md"
      - "آرایه‌ها (Arrays)": "advanced_data_types/029_arrays.md"
      - "ستون‌های تولید شده (Generated)": "advanced_data_types/030_generated_columns.md"
      - "انواع داده جستجوی متن": "advanced_data_types/031_text_search_types.md"
      - "رشته‌های بیتی (Bit String)": "advanced_data_types/032_bit_string.md"
      - "انواع داده بازه‌ای (Ranges)": "advanced_data_types/033_ranges.md"
      - "انواع داده ترکیبی (Composite)": "advanced_data_types/034_composite_types.md"
      - "کار با مقادیر Null": "advanced_data_types/035_nulls.md"
      - "قید یکتایی (Unique)": "advanced_data_types/036_unique_constraints.md"
      - "قید عدم تداخل (Exclusion)": "advanced_data_types/037_exclusion_constraints.md"
      - "قید کلید خارجی (Foreign Key)": "advanced_data_types/038_foreign_key_constraints.md"
  - "ایندکس‌گذاری":
      - "مقدمه‌ای بر ایندکس‌ها": "indexing/039_introduction_to_indexes.md"
      - "هیپ‌ها و CTIDها": "indexing/040_heaps_and_ctids.md"
      - "نمای کلی B-Tree": "indexing/041_b_tree_overview.md"
      - "کلیدهای اصلی در مقابل ایندکس‌های ثانویه": "indexing/042_primary_keys_vs_secondary_indexes.md"
      - "انواع کلید اصلی": "indexing/043_primary_key_types.md"
      - "کجا ایندکس اضافه کنیم؟": "indexing/044_where_to_add_indexes.md"
      - "گزینش‌پذیری ایندکس": "indexing/045_index_selectivity.md"
      - "ایندکس‌های ترکیبی": "indexing/046_composite_indexes.md"
      - "بازه‌های ترکیبی": "indexing/047_composite_range.md"
      - "ترکیب چندین ایندکس": "indexing/048_combining_multiple_indexes.md"
      - "ایندکس‌های پوششی": "indexing/049_covering_indexes.md"
      - "ایندکس‌های جزئی": "indexing/050_partial_indexes.md"
      - "ترتیب‌دهی ایندکس‌ها": "indexing/051_index_ordering.md"
      - "ترتیب‌دهی مقادیر Null در ایندکس‌ها": "indexing/052_ordering_nulls_in_indexes.md"
  - "ایندکس‌گذاری پیشرفته":
      - "ایندکس‌های تابعی": "advanced_indexing/053_functional_indexes.md"
      - "ایندکس‌های تکراری": "advanced_indexing/054_duplicate_indexes.md"
      - "ایندکس‌های هش": "advanced_indexing/055_hash_indexes.md"
      - "نام‌گذاری ایندکس‌ها": "advanced_indexing/056_naming_indexes.md"
  - "درک طرح‌های اجرایی":
      - "مقدمه‌ای بر Explain": "understanding_query_plans/057_introduction_to_explain.md"
      - "ساختار Explain": "understanding_query_plans/058_explain_structure.md"
      - "گره‌های اسکن": "understanding_query_plans/059_scan_nodes.md"
      - "هزینه‌ها و ردیف‌ها": "understanding_query_plans/060_costs_and_rows.md"
      - "دستور Explain Analyze": "understanding_query_plans/061_explain_analyze.md"
  - "کوئری‌های ترکیبی و تولید نتایج":
      - "مقدمه‌ای بر کوئری‌های پیشرفته": "generating_results/062_introduction_to_queries.md"
      - "اتصال متقاطع (CROSS JOIN)": "generating_results/063_cross_joins.md"
      - "اتصال داخلی (INNER JOIN)": "generating_results/064_inner_joins.md"
      - "اتصال خارجی (OUTER JOIN)": "generating_results/065_outer_joins.md"
      - "زیرکوئری‌ها (Subqueries)": "generating_results/066_subqueries.md"
      - "اتصال جانبی (LATERAL JOIN)": "generating_results/067_lateral_joins.md"
      - "دستور ROWS FROM": "generating_results/068_rows_from.md"
      - "پر کردن شکاف‌ها در سری‌های زمانی": "generating_results/069_filling_gaps_in_sequences.md"
      - "بهینه‌سازی و حذف زیرکوئری‌ها": "generating_results/070_subquery_elimination.md"
      - "ترکیب کوئری‌ها": "generating_results/071_combining_queries.md"
      - "توابع مجموعه‌ساز": "generating_results/072_set_generating_functions.md"
      - "ایندکس‌گذاری روی JOIN‌ها": "generating_results/073_indexing_joins.md"
